/*
_  ______   _____ _____ _____ _   _
| |/ / ___| |_   _| ____/___ | | | |
| ' / |  _    | | |  _|| |   | |_| |
| . \ |_| |   | | | |__| |___|  _  |
|_|\_\____|   |_| |_____\____|_| |_|

ANYWAY, YOU MUST GIVE CREDIT TO MY CODE WHEN COPY IT
CONTACT ME HERE +237656520674
YT: KermHackTools
Github: Kgtech-cmr
*/


const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}
module.exports = {
SESSION_ID: process.env.SESSION_ID || "CORNEH_TECH_254;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidU9xZi9WeWg1YjBCR2xQMCsrRmdLR3VHbVdiRm1xUVdhL2FsQTROSXdHUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTG1tNFJBNGppalIvVWphRkhQUDVMV0M4TElWOXFEaXN1QTA4SFFFT0YyMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1QWdxVUk3K0ZKN3l3RmF2YmV5V2FnejkrOTU2YXVCS2svcGo1dkJkQzI0PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJIZFhEd3pUZzltK04rQlVPeE45Lzk0VCtyWFdrMFk0ZVhsek9BMDhwckUwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1KcTFodkJGdU9iWWhtQjlHOFFPdE1xZGxoRWRpTWVTNTJnZ05UK0QxMEU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im4yeXFOU1RUYSsyY3NydFdPOHdJbWgvMHNrZU1vV2ZlVlREZlA5eFE5QzA9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0lWSWJQbEdYd2M5cVFXY28zSW9pemJFd3NWdDdGUEVJLzFaOHo1N3Rsaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaDc1Y0FTbWZIQ3p1cDNTdHJlRGpHU3p0S0lyTm5tRy9YalNKcDlxbllGaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjZXL2ZiQUNBT0FseC9UaitTWmJBWU5qaXdadCtsRmNGRFFZNkNNUWRvM01GeWlwUEZ1SzRreWJaemN0L0hIU1V5eW5wMjNOZEhkRy9UWkQ3clIyWGpRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTc4LCJhZHZTZWNyZXRLZXkiOiJkYVJwcjNlLzdrLzIzSUk3U3pwcHhkSGhXbHE0eXBweTZtZ2ZVRWJtOFlrPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJUdmViQlduRVE5ZWhBRzA1c2loNXdRIiwicGhvbmVJZCI6IjQ3ZmU5ZDliLTViYjEtNDIxOS1iOGM2LTMyMThkMGM4ZmMyOSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5R3o5SUU4Y1BxbVRSbGJENEpuUk5CSCsyYUU9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZDJXL2R3THVxN2FGNHJ5L2NZay9PN1liSEN3PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6Iks0RlZEN0ROIiwibWUiOnsiaWQiOiIyNTQ3OTU4OTE3MTE6MjJAcy53aGF0c2FwcC5uZXQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ05TVWs0QUNFSlhJMUw0R0dBUWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6ImFRYy9IZExMUjZ4bE9LaFdrcXcwTzBUR3JCa0tyV1ZZa2ZrY2tMRXFYVHc9IiwiYWNjb3VudFNpZ25hdHVyZSI6InRsNWZlYVRIOXVLZ3IyRjZUN3ZQMnU3eTJoY1U0cVFkM055UmFXR0d5YlJXZXdFYzZOaUVQQkxqazIvbXp4TGtMcHpETVZBdU9hQXkyUjhMUnNhV0FnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJmWHF5WUxVUzRBUDIvc1BlWVNHdHZucHYzK0F5TndoUk4xS1pxblJwS3c2NURXSnQyNW1JUjZ2TUpwbzM2Ull3aC9lMlBQUWNWWHZYV0FNK1psTDhqQT09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDc5NTg5MTcxMToyMkBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJXa0hQeDNTeTBlc1pUaW9WcEtzTkR0RXhxd1pDcTFsV0pINUhKQ3hLbDA4In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzQyMDIxNjY4LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUErSiJ9",
AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
MODE: process.env.MODE || "private",
AUTO_VOICE: process.env.AUTO_VOICE || "false",
AUTO_STICKER: process.env.AUTO_STICKER || "false",
AUTO_REPLY: process.env.AUTO_REPLY || "false",
ALIVE_IMG: process.env.ALIVE_IMG || "https://files.catbox.moe/kvk1wi.jpeg",
ALIVE_MSG: process.env.ALIVE_MSG || "_Hi 💁🏽 How Can I Assist You. Am alive Now._",
ANTI_LINK: process.env.ANTI_LINK || "true",
ANTI_BAD: process.env.ANTI_BAD || "true",
PREFIX: process.env.PREFIX || ".",
FAKE_RECORDING: process.env.FAKE_RECORDING || "false",
FAKE_TYPING: process.env.FAKE_TYPING || "true",
ALWAYS_ONLINE: process.env.ALWAYS_ONLINE || "true",
CURRENT_STATUS: process.env.CURRENT_STATUS || "true",
AUTO_REACT: process.env.AUTO_REACT || "false",
HEART_REACT: process.env.HEART_REACT || "false",
OWNER_REACT: process.env.OWNER_REACT || "false",
BOT_NAME: process.env.BOT_NAME || "『CORNEH V2』",
OMDB_API_KEY: process.env.OMDB_API_KEY || "76cb7f39", // omdbapi.com
};
